### ISSUE TITLE
ErrorException in YoutubeDownloader.php line 483: fopen(videos/Kavinsky_-_Protovision.mp4_temp_1478159094): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mokepark** [masihyeganeh/YoutubeDownloader#10]
I have this in controller and when open in browser getting "ErrorException in YoutubeDownloader.php line 483: fopen(videos/Kavinsky_-_Protovision.mp4_temp_1478159094): failed to open stream: No such file or directory" error,

I'm using laravel 5.3 

public function getInfo(){
        $youtube = new YoutubeDownloader('41_svUt5_e0');
        //$result = $youtube->getInfo();
        $result=$youtube->download(18);
        //dump($result);
    }

**Comment by mokepark** [comment]
I find the reason, beacuse i do not create the directory of  videos  ..........................., so i add the code to adding directory.
thanks

**Comment by masihyeganeh** [comment]
Thanks. I'll make it more clear in the README file

**Comment by mostafaznv** [comment]
I have a problem with returned $filePath from onFinalized()
`C:\xampp\htdocs\youtuder\public\videos\FC_Barcelona_vs_FC_Bayern_Munich_2015_（Champions_League_semi-final_Himno,Anthem ）.3gp`

can you see spaces after ')' ?



original video:
https://www.youtube.com/watch?v=sMq_A0ETURQ
