### ISSUE TITLE
Unable to get VEVO Videos

### ISSUE THREAD

**Issue by codezi** [masihyeganeh/YoutubeDownloader#14]
Thank you for your script, but
https://www.youtube.com/watch?v=dyfMD94d2Yc (Got url video, but can't play)
https://www.youtube.com/watch?v=0GoGcVs6pbU (Can't get)
Sorry for my bad English.

**Comment by masihyeganeh** [comment]
It is fixed now in version 2.7
Please test and reopen this issue if the error still persists.

**Comment by codezi** [comment]
Hi masihyeganeh,
Thank you for your reply and update.
I tested and now it can getinfo VEVO video.
But when I copy url and hit it to browser, I get
"Access to r6---sn-npoeen7k.googlevideo.com was denied
You don't have authorization to view this page.
HTTP ERROR 403"

**Comment by masihyeganeh** [comment]
I am using 2.7 and it can download both without any trouble:
<img width="594" alt="dyfMD94d2Yc" src="https://cloud.githubusercontent.com/assets/692335/22124329/a79c0ab4-dea4-11e6-9b0d-45ca1685ba07.png">
<img width="544" alt="0GoGcVs6pbU" src="https://cloud.githubusercontent.com/assets/692335/22124330/a81f9c4e-dea4-11e6-98ad-8098c85afbf3.png">

Please give me more details; Your OS, PHP Info and full exception message.
Thanks

**Comment by manivannan909** [comment]
some country you cant access that vevo video
