### ISSUE TITLE
No such a file vendor/autoload.php

### ISSUE THREAD

**Issue by manivannan909** [masihyeganeh/YoutubeDownloader#16]
No such a file vendor/autoload.php

As you said i used \Masih\YoutubeDownloader\YoutubeDownloader.php include but it getting error

Fatal error: Class 'Masih\YoutubeDownloader\YoutubeDownloader' not found

**Comment by masihyeganeh** [comment]
Depending on how you are using this code, you should include composer's autoload file.
If you downloaded zip archive or cloned this git, you should do a `composer install` then `vendor/autoload.php` is a valid path.
But it you used YoutubeDownloader as a dependency for your project, you should include autoload according to the file you are running. In this case, there is a good chance that composer's autoload file is already included. If not, please find the right path and include it. Sometimes it may be `../../autoload.php`.

This should work in both cases:
```php
if (file_exists(__DIR__.'/../../autoload.php')) {
	require __DIR__.'/../../autoload.php';
} else {
	require __DIR__.'/vendor/autoload.php';
}
```
