### ISSUE TITLE
Set filename

### ISSUE THREAD

**Issue by ezriharmusial** [masihyeganeh/YoutubeDownloader#17]
Peace!

Thank you Masih for this great work, I enjoy playing around with it! I am able to set the Filepath, but I want to ask: Is there a way to set filename before file saves?

**Comment by masihyeganeh** [comment]
Hello @ezriharmusial 
Unfortunately it's not possible not. Although it does not need a lot of work to implement it.
Maybe I'll add it in next release.
Pull requests are welcome anyway 😉

**Comment by ezriharmusial** [comment]
Thank You @masihyeganeh, I am just beginning with OOP, but maybe I can still contribute some.

**Comment by masihyeganeh** [comment]
Solved in v2.8.5. read [Readme](https://github.com/masihyeganeh/YoutubeDownloader#filename-sanitizing) file.
