### ISSUE TITLE
Undefined index: adaptive_fmts

### ISSUE THREAD

**Issue by donmarkus** [masihyeganeh/YoutubeDownloader#18]
Get this exception downloading 
`
$youtubeDownloader = new YoutubeDownloader('BE7E9EhyeUw');
        $youtubeDownloader->setPath('path');

  $youtubeDownloader->download(22, true);
`

**Comment by masihyeganeh** [comment]
This video is a special one that does not provide adaptive format. I believe that's not an exception. It's just a notice that I just fixed and will be solved in next version.

And about that `22`  itag. I don't see it in available full formats of the video:
<img width="452" alt="screen shot 1395-11-13 at 7 59 52 pm" src="https://cloud.githubusercontent.com/assets/692335/22515966/91b2cc3c-e8b9-11e6-95d3-0928f93e6b81.png">

**Comment by masihyeganeh** [comment]
It is fixed in version 2.8.2.
Thanks for reporting.
