### ISSUE TITLE
Is it possible to download it straight as an Mp3

### ISSUE THREAD

**Issue by HaydnG** [masihyeganeh/YoutubeDownloader#21]
Using ffmpeg to convert it from mp4 to mp3 is quite a slow process, is it possible to rip it stright to mp3?

**Comment by masihyeganeh** [comment]
Sorry, Youtube does not provide mp3 format of videos, but there are some itags dedicated to adaptive formats that provide only audio files in AAC, Opus and ... format (not mp3). You can use them to download less and convert faster
