### ISSUE TITLE
we need direct download link generator

### ISSUE THREAD

**Issue by praburamWAPKA** [masihyeganeh/YoutubeDownloader#22]
hi , we need direct download link generator also able to download vevo videos from youtube because that are encrypted by  signatures so please do as soon as possible

**Comment by masihyeganeh** [comment]
It is already implemented. Please read the Readme file

**Comment by praburamWAPKA** [comment]
Please create one function that print only url like 240p 144p 720p 1080p please this is my request

**Comment by ysk99** [comment]
i put the package to my shared hosting,,then composer update,,then create download.php,,when i run the download.php,,,it can't work,,,so please tell me how can i use it correctly,,thanks

**Comment by ysk99** [comment]
the download.php is 
<?php
set_time_limit(0); // Downloading a video may take a lot time

include 'vendor/autoload.php';

use Masih\YoutubeDownloader\YoutubeDownloader;

$youtube = new YoutubeDownloader('gmFn62dr0D8');

$youtube->download();

**Comment by ysk99** [comment]
<?php
set_time_limit(0); // Downloading a video may take a lot time

include 'vendor/autoload.php';

use Masih\YoutubeDownloader\YoutubeDownloader;

$youtube = new YoutubeDownloader('gmFn62dr0D8');

$youtube->download();

**Comment by ysk99** [comment]
it also show a 500 (Internal Server Error)

**Comment by praburamWAPKA** [comment]
@ysk99 Download is Working Well... it takes sometime to download so look at  the folder

**Comment by masihyeganeh** [comment]
@praburamWAPKA You can achieve this by using `getInfo(true)` method. It has download links and qualities.

@ysk99 Make sure the download folder and temp folders are writable. Read your server's error log for more detailed message

**Comment by praburamWAPKA** [comment]
Oh My Goddd Finally i found it thank youuu Soo Much.... You are Awesome

**Comment by ysk99** [comment]
@praburamWAPKA there is so much code ,how to find the download link?thanks

**Comment by praburamWAPKA** [comment]
no you wrong Many of them 404 cause of cipher encrypted this is rare which supports vevo  now im Spliting Each links in to 320p 720p 240p 144p

**Comment by ysk99** [comment]
@praburamWAPKA  hi,have you find the link which can download directly??

**Comment by Sam-Lab** [comment]
Hello. I write:
`$link->download($itag, true, false);`
And shows error:
`An error occurred when downloading video`
I use Laravel. Can you help me?

**Comment by RaihanSojeb** [comment]
Thanks finally I got a online youtube downloader site http://tubebd24.com


Thank you for such a great script
