### ISSUE TITLE
Direct Link Generator Based on URL ID

### ISSUE THREAD

**Issue by praburamWAPKA** [masihyeganeh/YoutubeDownloader#24]
demo :-  http://new.moviesdam.in/index.php?id=iQtDYrV5UDI

`<?php

include 'vendor/autoload.php';

use Masih\YoutubeDownloader\YoutubeDownloader;

$youtube = new YoutubeDownloader($_GET['id']);

$json = $youtube->getInfo(true);

 $jsons = [];
$jsons[] = json_encode($json);
$tik= $jsons[0];

$yummy = json_decode($tik , true);

$url0= $yummy['full_formats'][0]['url']; 
$url00= $yummy['full_formats'][0]['quality'];
$url000= $yummy['full_formats'][0]['filename'];
$url0000= $yummy['full_formats'][0]['type'];

echo '<a href="'.$url0.'&title=[Prabhuram]'.$url000.'">Download '.$url00.' [ '.$url0000.' ]</a>
<br/>' ;

$url1= $yummy['full_formats'][1]['url']; 
$url11= $yummy['full_formats'][1]['quality'];
$url111= $yummy['full_formats'][1]['filename'];
$url1111= $yummy['full_formats'][1]['type'];

echo '<a href="'.$url1.'&title=[Praburam]'.$url111.'">Download '.$url11.' [ '.$url1111.' ]</a>
<br/>' ;

$url2= $yummy['full_formats'][2]['url']; 
$url22= $yummy['full_formats'][2]['quality'];
$url222= $yummy['full_formats'][2]['filename'];
$url2222= $yummy['full_formats'][2]['type'];

echo '<a href="'.$url2.'&title=[Praburam]'.$url222.' ">Download '.$url22.' [ '.$url2222.' ]</a>
<br/>' ;

$url3= $yummy['full_formats'][3]['url']; 
$url33= $yummy['full_formats'][3]['quality'];
$url333= $yummy['full_formats'][3]['filename'];
$url3333= $yummy['full_formats'][3]['type'];

echo '<a href="'.$url3.'&title=[Praburam]'.$url333.'">Download '.$url33.' [ '.$url3333.' ]</a>
<br/>' ;

`

**Comment by masihyeganeh** [comment]
Why bother like that?
It is simple as this:
```php
<?php
include 'vendor/autoload.php';

use Masih\YoutubeDownloader\YoutubeDownloader;

$youtube = new YoutubeDownloader($_GET['id']);
$info = $youtube->getInfo(true);

foreach($info->full_formats as $format) {
    echo '<a href="' . $format->url . '">' . $format->quality . ' [' . $format->type . ']</a><br>';
}
```
