### ISSUE TITLE
failed to open stream: No such file or directory in F:\Data_Xampp\htdocs\wordpress\wp-content\plugins\audiotext\vendor\masih\youtubedownloader\Masih\YoutubeDownloader\YoutubeDownloader.php on line 824

### ISSUE THREAD

**Issue by TendiF** [masihyeganeh/YoutubeDownloader#27]
what i got even i use default function, that happen in fopen($file,'a')

**Comment by TendiF** [comment]
`	protected function downloadFile($url, $file, callable $onProgress, callable $onFinish)
	{
		$videoFile = fopen($file, 'a');
		$options = array(
			'sink' => $videoFile,
			'verify' => false,
			'timeout' => 0,
			'connect_timeout' => 50,
			'progress' => $onProgress,
			'cookies' => new CookieJar(false, [['url' => 'https://www.youtube.com/watch?v=' . $this->videoId]])
		);

		$request = new Request('get', $url);
		$promise = $this->webClient->sendAsync($request, $options);
		$promise->then(
			function (ResponseInterface $response) use ($videoFile, $file, $onFinish) {
				fclose($videoFile);

				$size = filesize($file);
				$remained = intval((string)$response->getHeader('Content-Length')[0]);

				$onFinish($size, $remained);
			},
			function (GuzzleException $e) {
				if ($e instanceof ClientException && $e->hasResponse())
					throw new YoutubeException($e->getResponse()->getReasonPhrase(), 4);
				else
					throw new YoutubeException($e->getMessage(), 4);
			}
		);

		try {
			$promise->wait();
		} catch (\RuntimeException $e) {
			throw new YoutubeException('An error occurred when downloading video', 20, $e);
		}
	}`

**Comment by masihyeganeh** [comment]
Check with the new 2.9.0 version and open this issue if it's not working
