### ISSUE TITLE
An error occurred when downloading video

### ISSUE THREAD

**Issue by Sam-Lab** [masihyeganeh/YoutubeDownloader#28]
Hello. Im using your library with laravel. When i generates link for download, i givens error - An error occurred when downloading video.
My function:
`public function download($video, $itag){

$link = new YoutubeDownloader($video);

$link->setDefaultItag($itag);

$link->download();

}`

And second error is - 'Client error: `GET https://r3---sn-hja50u-j3jl.googlevideo.com/videoplayback?ratebypass=yes&initcwndbps=1331250&ipbits=0&ip=91.244.6.9&itag=22&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&expire=1510243699&mime=video%2Fmp4&mt=1510222008&mm=31&mn=sn-hja50u-j3jl&id=o-ADtt4uw9o8hebxu4-ntlKRS_VDRoXb3FwSu94d_OQ1pV&key=yt6&source=youtube&dur=268.260&mv=m&ei=EykEWu6UFI2pcqbYDw&ms=au&lmt=1508345753151039&requiressl=yes&pl=18` resulted in a `403 Forbidden` response'.
Please, hellp me!

**Comment by Smythu** [comment]
yeah, some links dont seem to work. same with this one: https://www.youtube.com/watch?v=tKi9Z-f6qX4

**Comment by masihyeganeh** [comment]
@Sam-Lab:
Check with the new 2.9.0 version and open this issue if it's not working.

@Smythu:
This link works too with the new version.
