### ISSUE TITLE
Error json_encode with non UTF8 sentence

### ISSUE THREAD

**Issue by fredOnGitHub** [masihyeganeh/YoutubeDownloader#30]
Hello,
from your example :

`<?php`
`    require_once('/Users/<YOUR_HOME_DIRECTORY>/.composer/vendor/autoload.php');`
`    use Masih\YoutubeDownloader\YoutubeDownloader;`
`    $youtube = new YoutubeDownloader('IMLp3Mn6I3s');`
`    $result = $youtube->getInfo();`
`    header('Content-type: application/json');`
`    print json_encode($result);`
`?>`

That's ok with 'gmFn62dr0D8' idVideo but not with 'IMLp3Mn6I3s' because there is a UTF-8 encodage json error 

Even if i do that : 
`<!DOCTYPE html>`
`<html>`
`<head>`
`    <meta charset="utf-8" />`
`</head>`
`<body>`
`<?php`
`    require_once('/Users/<YOUR_HOME_DIRECTORY>/.composer/vendor/autoload.php');`
`    use Masih\YoutubeDownloader\YoutubeDownloader;`
`    $youtube = new YoutubeDownloader('IMLp3Mn6I3s');`
`    $result = $youtube->getInfo();`
`    header('Content-type: application/json');`
`    print json_encode($result);`
`?>`
`</body>`
`</html>`

You can see the UTF-8 error with this program : 

`<?php`
`require_once('/Users/<YOUR_HOME_DIRECTORY>/.composer/vendor/autoload.php');`
`use Masih\YoutubeDownloader\YoutubeDownloader;`
`function a($b){`
`    print ("<pre>");`
`    var_dump ($b);`
`    print ("</pre>");`
`}`
`//http://php.net/manual/en/function.json-last-error.php`
`function aa(){`
`    switch (json_last_error()) {`
`        case JSON_ERROR_NONE:`
`            echo ' - No errors';`
`        break;`
`        case JSON_ERROR_DEPTH:`
`            echo ' - Maximum stack depth exceeded';`
`        break;`
`        case JSON_ERROR_STATE_MISMATCH:`
`            echo ' - Underflow or the modes mismatch';`
`        break;`
`        case JSON_ERROR_CTRL_CHAR:`
`            echo ' - Unexpected control character found';`
`        break;`
`        case JSON_ERROR_SYNTAX:`
`            echo ' - Syntax error, malformed JSON';`
`        break;`
`        case JSON_ERROR_UTF8:`
`            echo ' - Malformed UTF-8 characters, possibly incorrectly encoded';`
`        break;`
`        default:`
`            echo ' - Unknown error';`
`        break;`
`    }`
`    echo PHP_EOL;`
`}`
`$video_id='IMLp3Mn6I3s';`
`$youtube = new YoutubeDownloader($video_id);`
`$result = $youtube->getInfo();//il est en objet`
`$result = $result->full_formats[0]->filename;`
`echo"<br>Origine : $result";`
`a("Origine : $result");echo"<br>";`
`echo "<br>---------------";`
`$json  = json_encode($result);`
`echo "<br>1)";`
`echo $json;`
`echo "<br>2)";`
`a($json);`
`aa();`
`echo"<br>---------------";`
`$json  = json_encode(utf8_encode($result));`
`echo "<br>1)";`
`echo $json;`
`echo "<br>2)";`
`a($json);`
`aa();`
`echo"<br>---------------";`
`?>`

**Comment by masihyeganeh** [comment]
I can't reproduce that. here's what it do in a telegram bot
![photo_2018-01-27_16-22-48](https://user-images.githubusercontent.com/692335/35472115-5b15736a-037e-11e8-9d22-c31847a57b5b.jpg)

**Comment by fredOnGitHub** [comment]
Hello I confirme with 'IMLp3Mn6I3s' id video you can download.

But if i want save the info with json like your example i get UTF-8 encodage error.

Here the result of the code at the top of the page.
![json_error](https://user-images.githubusercontent.com/9338756/35476797-7ce94650-03b6-11e8-8aa6-44c5c3f29b08.png)

You seem have this application in your mobile that's nice !!
I have searched on android 'youtube downloader' without results;
