### ISSUE TITLE
getInfo() retrieve 100 infos video max . Youtube problem knows apparently ?

### ISSUE THREAD

**Issue by fredOnGitHub** [masihyeganeh/YoutubeDownloader#31]
Hello 

this **id upload** 'UUNE6x5xiywiIdpmUC2d6eJw' contains no less than 1352 videos 

but with 

$idUPLOAD='UUNE6x5xiywiIdpmUC2d6eJw';
$youtube = new YoutubeDownloader($idUPLOAD);
$result = $youtube->getInfo();
a($result);

i get a table of 100 elements max

**You haven't all the list.**

Even doing this : 
$url='https://www.youtube.com/list_ajax?style=json&action_get_list=1&list=UUNE6x5xiywiIdpmUC2d6eJw';
$s = file_get_contents($url); 
header('Content-type: application/json');
print_r ($s);

I get a table of 100 elements max

But i have remarqued that if you change '...get_list=**1**&...' to '...get_list=**2**&...' you have another list...
The next 101->200 ? 

It's look like YouTube Data API v3 results which are paginated...

**Comment by masihyeganeh** [comment]
Thanks for reporting.
I should add this in next version.
