### ISSUE TITLE
Signature Value not adding

### ISSUE THREAD

**Issue by litefast** [masihyeganeh/YoutubeDownloader#32]
Hello,

I don't really care if downloads or not,but shouldn't there is a signature value in the download links.

Well,guess what!!! It's not being added.

Please check the link http://ytapi.atspace.cc/?id=xpbe-B0TO80

I installed via Composer.

**Comment by masihyeganeh** [comment]
> shouldn't there is a signature value in the download links

Not necessarily. This video is age restricted and Youtube won't give the signature without signing in. 

<img width="415" alt="screen shot 1396-11-15 at 1 19 14 am" src="https://user-images.githubusercontent.com/692335/35771905-b1f32b0c-0949-11e8-832c-e3d707526cc9.png">

**Comment by litefast** [comment]
But, I have seen genyoutube.net work with this type of video.Also YouTube-DL(Python) is working with this video.How they are doing this.

Any Idea??

**Comment by litefast** [comment]
Don't you currently support Age-restricted video??

**Comment by masihyeganeh** [comment]
I'm closing this issue because I don't have any plan to add authentication to this library and it is needed for age-restricted videos.
