### ISSUE TITLE
Download not working for certain files

### ISSUE THREAD

**Issue by litefast** [masihyeganeh/YoutubeDownloader#33]
Hi,

Found Some videos which are not downloading.

Here's the output http://ytapi.atspace.cc/index.php?id=ASr_wCswSus

None of the video from this File's Uploader/Author is downloading.

Can please have a look.

**Comment by Smythu** [comment]
as I see you fixed it? what did you do?

**Comment by rayhanz** [comment]
Nothing used reserve proxy :p by the way I am @litefast

**Comment by Smythu** [comment]
could you tell me how you implemented a reverse proxy?

**Comment by masihyeganeh** [comment]
The video you mentioned is country-restricted.
the new 2.9.0 version will throw better errors. try it if you want.

**Comment by rayhanz** [comment]
@Smythu try googling for "nginx reverse proxy".But be aware you must need VPS or Dedicated server.I suggest you use OVH

**Comment by Smythu** [comment]
it is working now with version 2.9.0. thanks to @masihyeganeh
