### ISSUE TITLE
mp3

### ISSUE THREAD

**Issue by checker82** [masihyeganeh/YoutubeDownloader#34]
If you can tell me how to get only MP 3 and do not ge tgetPlaylistInfo() .thanks

**Comment by Thunder33345** [comment]
as far as i know you have to convert it...
i did it using ffmpeg to convert it into mp3
tho i doubt this is the most effective method

**Comment by checker82** [comment]
thanks. I just want to get a link directly to ffmpeg. We can not get a direct download link

**Comment by Thunder33345** [comment]
download = https://www.ffmpeg.org/download.html
warper = https://github.com/PHP-FFMpeg/PHP-FFMpeg
you will need to download the vid and pass the file to ffmpeg ffmpeg does not download this for you

**Comment by masihyeganeh** [comment]
Yeah, as of now the only way to download mp3 file is to download one of files provided by this library (adaptives are preferred) and convert it by `ffmpeg` or similar apps.
In far future I may write a pure-php converter for it.
