### ISSUE TITLE
how can I add a bootstrap progressbar which works with onProgress

### ISSUE THREAD

**Issue by Smythu** [masihyeganeh/YoutubeDownloader#35]
title says it. i use a conversion.php to download and convert to certrain files, by passing the id in javascript on my index.php;
```
<script type="text/javascript">                      
	    var auto_refresh = setInterval(
		(function () {
		    $("#converting").load("lib/lib.conversion.php?id=<?php echo $id; ?>"); //Load the content into the div
		}), 1000);
</script> 
```

any ideas?

**Comment by masihyeganeh** [comment]
You can use [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) or something like that.
Or just save this progress in a file in server and read it periodically from client
