### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://r4---sn-25ge7nsl.googlevide

### ISSUE THREAD

**Issue by Smythu** [masihyeganeh/YoutubeDownloader#38]
seems like youtube did something against it?
I cannot download any video anymore. And it is not regionrestricted.

**Comment by Smythu** [comment]
ERROR:
`Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://r1---sn-25ge7nl6.googlevideo.com/videoplayback?gir=yes&pl=19&dur=636.923&expire=1521828048&ratebypass=yes&itag=18&c=WEB&ipbits=0&mt=1521805844&mv=u&ms=au%2Crdu&source=youtube&mime=video%2Fmp4&clen=13048944&requiressl=yes&mm=31%2C29&mn=sn-25ge7nl6%2Csn-25glene7&key=yt6&ei=cOy0WtTrEsHBVdadhTA&id=o-AOQ1TjZSw1fX5YUlPuhJBugXKFauhcjMNvyvGpH0jHYy&lmt=1521056161131411&fvip=3&ip=54.38.180.75&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&signature=` resulted in a `403 Forbidden` response in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception`

**Comment by masihyeganeh** [comment]
It's working fine here. Give me the video-id of that video

**Comment by Smythu** [comment]
Im getting this error for every video id. Its working fine on a different server. Does youtube block ips if they are getting informations to often?

**Comment by Smythu** [comment]
SOLVED:
somehow my cache folder only had chmod 755, changed it to 777 - working fine.
