### ISSUE TITLE
signature decrypt not working anymore

### ISSUE THREAD

**Issue by Smythu** [masihyeganeh/YoutubeDownloader#40]
seems like youtube changed something. I cannot download ANYTHING, it shows me the link but its redirecting me to a blank page.

**Comment by Smythu** [comment]
seems like it has something to do with the signatures?
i can download not ciphered stuff tho

**Comment by masihyeganeh** [comment]
Without at least one video ID to test, I can't do much.
I can download videos here. please check if Google blocked you or not

**Comment by masihyeganeh** [comment]
It should be fixed in 2.9.2. Test it please

**Comment by zxq2233** [comment]
@masihyeganeh Please test the video id: nk8_rNFdlTA
