### ISSUE TITLE
get size video

### ISSUE THREAD

**Issue by mosayebbameri** [masihyeganeh/YoutubeDownloader#43]
hi 
if you can please add size video in json for any Quality.
i try that add option for class but i can't

**Comment by ergauravsethi376** [comment]
Hi
I also stuck over this issue can any one help me over it @mosayebbameri did you find solution for it , if yes can you please help me over it 

Thanks in advance PAL !!

**Comment by masihyeganeh** [comment]
This library generates direct links. you can easily have their size by requesting them.
Here is a simple function to get that:
```PHP
function getSize($url) {
    $headers = get_headers($url);
    foreach ($headers as $header) {
        if (stripos($header, 'Content-Length: ') === 0) {
            return substr($header, 16);
        }
    }
    return -1;
}


$youtube = new YoutubeDownloader('gmFn62dr0D8');
$info = $youtube->getInfo()

$size = getSize($info->full_formats[0]->url);
echo $size;
```
