### ISSUE TITLE
error downloading video?

### ISSUE THREAD

**Issue by shamsat** [masihyeganeh/YoutubeDownloader#44]
Hi,
When i run the php script to download video get this error in php.log:
`[13-Aug-2018 09:48:21 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: sink must not be a boolean in /home/user/www/yd/vendor/guzzlehttp/guzzle/src/Client.php:384
Stack trace:
#0 /home/shams/www/yd/vendor/guzzlehttp/guzzle/src/Client.php(273): GuzzleHttp\Client->applyOptions(Object(GuzzleHttp\Psr7\Request), Array)
#1 /home/user/www/yd/vendor/guzzlehttp/guzzle/src/Client.php(99): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#2 /home/user/www/yd/vendor/masih/youtubedownloader/Masih/YoutubeDownloader/YoutubeDownloader.php(845): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#3 /home/user/www/yd/vendor/masih/youtubedownloader/Masih/YoutubeDownloader/YoutubeDownloader.php(1072): Masih\YoutubeDownloader\YoutubeDownloader->downloadFile('https://r1---sn...', 'videos/Se\xC3\xB1ora_...', Object(Closure), Object(Closure))
#4 /home/user/www/yd/vendor/masih/youtubedownloader/Masih/YoutubeDo in /home/user/www/yd/vendor/guzzlehttp/guzzle/src/Client.php on line 384`

**Comment by masihyeganeh** [comment]
It should be fixed in 2.9.2. Test it please
