### ISSUE TITLE
masih youtube downloader not working on online server

### ISSUE THREAD

**Issue by ramrajkapar** [masihyeganeh/YoutubeDownloader#45]
I'm using masihyeganeh@outlook.com package in my project. On local server youtube video of id v= JFcgOboQZ08 is working but in the server if I want to download in my online running server not downloading. and showing error   "Masih \ YoutubeDownloader \ YoutubeException (20)
An error occurred when downloading video". What is the problem, please solve it.

**Comment by masihyeganeh** [comment]
I just tested it. It didn't succeed at first, but after a few tries, it did. I could not pin point the problem, but as a workaround, delete every file in `cache` folder and try again a few times.

**Comment by masihyeganeh** [comment]
It should be fixed in 2.9.2. Test it please
