### ISSUE TITLE
Access to r2---sn-q4fl6ner.googlevideo.com was denied

### ISSUE THREAD

**Issue by harisnaeemofficial** [masihyeganeh/YoutubeDownloader#48]
Access to r2---sn-q4fl6ner.googlevideo.com was denied

You don't have authorization to view this page.

HTTP ERROR 403

URL : https://www.youtube.com/watch?v=q2gICJFG6uw

Signature is getting in seperate array video size showing 0mb in videos folder

Even poster image is blank 

image URL : https://i.ytimg.com//vi//q2gICJFG6uw//hqdefault.jpg

Working image URL is :https://i.ytimg.com/vi/q2gICJFG6uw/hqdefault.jpg

Output is : 

{"title":"Baaghi 2: Ek Do Teen Song | Jacqueline Fernandez |Tiger Shroff | Disha P| Ahmed K | Sajid Nadiadwala","image":{"max_resolution":"https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/maxresdefault.jpg","high_quality":"https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/hqdefault.jpg","medium_quality":"https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/mqdefault.jpg","standard":"https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/sddefault.jpg","thumbnails":["https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/default.jpg","https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/0.jpg","https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/1.jpg","https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/2.jpg","https:\/\/i.ytimg.com\/vi\/q2gICJFG6uw\/3.jpg"]},"length_seconds":"97","duration":"00:01:37","video_id":"q2gICJFG6uw","views":"58119409","rating":4,"author":"T-Series","captions":[],"full_formats":[{"sp":"signature","type":"video\/mp4; codecs=\"avc1.64001F, mp4a.40.2\"","url":"https:\/\/r2---sn-q4fl6ner.googlevideo.com\/videoplayback?mm=31%2C26&pl=22&mn=sn-q4fl6ner%2Csn-qxo7rn7s&id=o-AKt0wHtG_CrggtZ9YePOZkQbq6th4vMoGEwhrXbPy5Qb&dur=96.757&requiressl=yes&mime=video%2Fmp4&ip=69.162.84.122&key=yt6&itag=22&mt=1536817475&mv=u&ms=au%2Conr&lmt=1521494634513868&fvip=2&source=youtube&c=WEB&ei=CPyZW5qbDYjkwQGxuY-oDQ&sparams=dur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ratebypass=yes&ipbits=0&expire=1536839784","s":"D1D10EB24D864023813D86EB96D4C72703D6657317.1A228B9CB1D908E852FF584F5BC56A1D733D96A5E","itag":"22","quality":"hd720","filename":"Baaghi_2_Ek_Do_Teen_Song_Jacqueline_Fernandez_Tiger_Shroff_Disha_P_Ahmed_K_Sajid_Nadiadwala.mp4"}

**Comment by masihyeganeh** [comment]
It is fixed in v2.9.5.
Please test and reopen this issue if the problem persists.
Thanks
