### ISSUE TITLE
no adaptive_formats

### ISSUE THREAD

**Issue by Gemorroj** [masihyeganeh/YoutubeDownloader#49]
for this video https://www.youtube.com/watch?v=zWP8KEvBwyo `adaptive_formats` is empty.

**Comment by masihyeganeh** [comment]
There is no problem in my PC:
<img width="422" alt="screen shot 1397-08-06 at 3 09 12 pm" src="https://user-images.githubusercontent.com/692335/47615410-9f3f3e00-dac3-11e8-82ba-5f03fe7446d3.png">
