### ISSUE TITLE
Access to googlevideo.com was denied HTTP ERROR 403

### ISSUE THREAD

**Issue by zxq2233** [masihyeganeh/YoutubeDownloader#51]
i'm already update to v.2.9.3.
The video still access deny. please help.

**Comment by zxq2233** [comment]
![baidushurufa_2018-9-29_7-1-4](https://user-images.githubusercontent.com/14195738/46250797-3be6cf80-c475-11e8-8c5f-52931ac74e67.png)

**Comment by sanishan** [comment]
look like youtube has changed the signature decoding method,  I hope someone update!

**Comment by masihyeganeh** [comment]
It is fixed in v2.9.5.
Please test and reopen this issue if the problem persists.
Thanks
