### ISSUE TITLE
Video with signature

### ISSUE THREAD

**Issue by expprogdev** [masihyeganeh/YoutubeDownloader#57]
Can you please tell us when the problem with downloading a video with signature will be solved? Now, the video that has the [s] property is not downloading.

**Comment by masihyeganeh** [comment]
This kind of issues won't help solving anything.
Consider sending a PR or at least giving a videoId to test

**Comment by expprogdev** [comment]
For example:

**Comment by expprogdev** [comment]
[0] => stdClass Object
--
  | (
  | [type] => video/mp4; codecs="avc1.42001E, mp4a.40.2"
  | [sp] => signature
  | [quality] => medium
  | [itag] => 18
  | [url] => https://r1---sn-5hnekn7l.googlevideo.com/videoplayback?key=yt6&ei=Xof2W-ezN8aMVoKbv7AJ&expire=1542904767&mv=u&txp=5531432&clen=17487704&c=WEB&fvip=1&ratebypass=yes&gcr=nl&source=youtube&lmt=1539159732556852&gir=yes&ipbits=0&id=o-ADs_OFtoSn1XiR6-_QBs7cQ7UDLN_att1nz6U7IYxVM3&dur=231.619&mime=video%2Fmp4&ms=au%2Crdu&requiressl=yes&mt=1542882577&pl=25&itag=18&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mm=31%2C29&ip=185.53.160.218&mn=sn-5hnekn7l%2Csn-5hne6nlr
  | **[s] => 77F47FC49A8FCE78AE12068EFF2D22B800A8E5FA1AD.80C9D4A08048D7A44D6FD8027351F7F7C66CD0A40A2**
  | [filename] => DJ_Snake_-_Taki_Taki_ft._Selena_Gomez,_Ozuna,_Cardi_B.mp4
  | )

**Comment by masihyeganeh** [comment]
Check if it is fixed in 2.9.7. reopen this issue if the problem persists.
