### ISSUE TITLE
Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 402 [reason phrase] Payment Required [url] 

### ISSUE THREAD

**Issue by hussein-shakiba** [masihyeganeh/YoutubeDownloader#6]
hi 
i run code but show this erro what???
Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 402 [reason phrase] Payment Required [url]

**Comment by masihyeganeh** [comment]
Hey
Can you please give me it's video id?
Maybe it's just available in Youtube Red.

**Comment by jauwh974** [comment]
Hi, same problem for me with any video id i got the same warning about Payment Required.
Any solution please ?

**Comment by masihyeganeh** [comment]
Give me some video id to test

**Comment by jauwh974** [comment]
It's ok. My bad ! Don't know why but my server IP is banned from Google so I use another one.
