### ISSUE TITLE
There is no format for download

### ISSUE THREAD

**Issue by YazanAldbaisy** [masihyeganeh/YoutubeDownloader#63]
I tried to use this package for more than video and playlist and each time I get this Exception 
Masih\YoutubeDownloader\YoutubeDownloader::downloadVideo
C:\Users\Yazan\Desktop\Youtube Downloader\YTD\vendor\masih\youtubedownloader\Masih\YoutubeDownloader\YoutubeDownloader.php:974

**Comment by masihyeganeh** [comment]
Sorry, this package is abandoned and I'm not maintaining it anymore
