### ISSUE TITLE
Need Help Urgently on the code

### ISSUE THREAD

**Issue by enckwab** [masihyeganeh/YoutubeDownloader#8]
Thank you for the script. I want to implement it on my website www.ghdownloads.com. I want to test it on localhost first but I always get this error:

THIS IS THE ERROR
Warning: include(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\ydl2\index.php on line 4

Warning: include(): Failed opening 'vendor/autoload.php' for inclusion (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\ydl2\index.php on line 4

Fatal error: Class 'Masih\YoutubeDownloader\YoutubeDownloader' not found in C:\xampp\htdocs\ydl2\index.php on line 7

**Comment by masihyeganeh** [comment]
Hello,
It seems like you are not downloading the package via [composer](https://getcomposer.org/).
Please confirm that you are installing it by `composer install` and the `vendor` folder exists in your project

**Comment by enckwab** [comment]
It seems like I need help on how I can do it from scratch so please if you can help me on that. I'm not good at php and I thought just unzipping your zip content into a folder will easily work.

**Comment by enckwab** [comment]
Anyway masihyeganeh thank you very much. I'm looking forward to hear from you again.

**Comment by enckwab** [comment]
I want to do is for my users to download my videos I upload directly from my site.

**Comment by masihyeganeh** [comment]
If you are not using Composer, this project work for you. please go to the link in my first response and read how to use composer to get packages.

**Comment by enckwab** [comment]
Ok. will do so and let you know. Anyway can I get other means to contact you other than github?
